version: '3.8'

services:
  extra-ed-db:
    image: postgres
    container_name: extra-ed-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: extra-ed-db
    volumes:
      - extra-ed-db:/var/lib/postgresql/data

  extra-ed-app-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: extra-ed-app-api
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - extra-ed-db
    volumes:
      - ./:/app

volumes:
  extra-ed-db:
